public enum CombinationProbabilityAlgorithm {
    EXHAUSTIVE_SEARCH, OPPONENT_EXHAUSTIVE_SEARCH, PARALLEL_EXHAUSTIVE_SEARCH,
    PARALLEL_OPPONENT_EXHAUSTIVE_SEARCH, OPPONENT_MONTE_CARLO, MONTE_CARLO, SIMPLIFIED_EXHAUSTIVE_SEARCH;
}
